// Part B runner: audit every seed article and write reports. Not production
// code — it reads the article export and writes audit-reports/. Idempotent:
// re-running overwrites the reports deterministically.
//
//   node --experimental-transform-types --import ./scripts/ts-register.mjs \
//     packages/audit/scripts/run-audit.ts

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCorpus } from '@quranbench/corpus';
import { auditArticle, createContext, renderMarkdown } from '@quranbench/audit';
import type { ArticleReport, Finding } from '@quranbench/audit';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const ARTICLES_DIR = path.resolve(REPO_ROOT, '../quranandfaith-export');
const OUT_DIR = path.resolve(REPO_ROOT, 'audit-reports');

function flaggedLine(f: Finding): string {
  return `- **[${f.severity}]** ${f.summary} — line ${f.location.line}: \`${f.location.excerpt}\``;
}

function uncheckedLine(f: Finding): string {
  return `- ${f.summary} — line ${f.location.line}`;
}

function renderSummary(reports: ArticleReport[]): string {
  const ranked = [...reports].sort(
    (a, b) => b.workScore - a.workScore || b.counts.flagged - a.counts.flagged || a.slug.localeCompare(b.slug),
  );
  const out: string[] = [];
  out.push('# Audit summary — seed articles');
  out.push('');
  out.push(
    `_Generated by \`@quranbench/audit\` against corpus ${reports[0]?.corpusVersion ?? '—'} (Tanzil Uthmani text, Leeds QAC morphology). Automated checks only; every flag is for a human decision and **nothing was corrected**._`,
  );
  out.push('');
  out.push(
    'Review score weights flagged findings by severity (high = 5, medium = 2, low = 1). It ranks how much verification work each article needs, not how wrong it is.',
  );
  out.push('');
  out.push('## Ranking by verification work');
  out.push('');
  out.push('| Rank | Article | Checked | Verified | Flagged | Unchecked | Score |');
  out.push('| ---: | --- | ---: | ---: | ---: | ---: | ---: |');
  ranked.forEach((r, i) => {
    out.push(
      `| ${i + 1} | [${r.title}](${r.slug}.md) | ${r.counts.checked} | ${r.counts.verified} | ${r.counts.flagged} | ${r.counts.unchecked} | ${r.workScore} |`,
    );
  });
  out.push('');

  out.push('## Flagged claims by article (worst first)');
  out.push('');
  const withFlags = ranked.filter((r) => r.counts.flagged > 0);
  if (withFlags.length === 0) out.push('_No article had any flagged claim._');
  for (const r of withFlags) {
    out.push(`### ${r.title} — \`${r.file}\` · score ${r.workScore}`);
    out.push('');
    for (const f of r.findings.filter((x) => x.status === 'flagged')) out.push(flaggedLine(f));
    const unchecked = r.findings.filter((x) => x.status === 'unchecked');
    if (unchecked.length) {
      out.push('');
      out.push('Could not be checked automatically:');
      for (const f of unchecked) out.push(uncheckedLine(f));
    }
    out.push('');
  }

  const clean = ranked.filter((r) => r.counts.flagged === 0);
  if (clean.length) {
    out.push('## Articles with no flags');
    out.push('');
    for (const r of clean) {
      out.push(
        `- **${r.title}** (\`${r.file}\`) — ${r.counts.verified} verified, ${r.counts.unchecked} unchecked${r.counts.checked === 0 ? ' _(no checkable claims — stub or non-Quranic page)_' : ''}`,
      );
    }
    out.push('');
  }
  return out.join('\n');
}

function main(): void {
  const ctx = createContext(loadCorpus());
  mkdirSync(OUT_DIR, { recursive: true });

  const files = readdirSync(ARTICLES_DIR)
    .filter((f) => f.endsWith('.md'))
    .sort();

  const reports: ArticleReport[] = [];
  for (const file of files) {
    const markdown = readFileSync(path.join(ARTICLES_DIR, file), 'utf8');
    const report = auditArticle(ctx, { file, markdown });
    reports.push(report);
    writeFileSync(path.join(OUT_DIR, `${report.slug}.md`), renderMarkdown(report));
    writeFileSync(path.join(OUT_DIR, `${report.slug}.json`), JSON.stringify(report, null, 2) + '\n');
  }

  writeFileSync(path.join(OUT_DIR, 'SUMMARY.md'), renderSummary(reports));
  const index = reports.map((r) => ({
    slug: r.slug,
    title: r.title,
    file: r.file,
    corpusVersion: r.corpusVersion,
    counts: r.counts,
    workScore: r.workScore,
    flagged: r.findings
      .filter((f) => f.status === 'flagged')
      .map((f) => ({ kind: f.kind, severity: f.severity, line: f.location.line, summary: f.summary })),
  }));
  writeFileSync(path.join(OUT_DIR, 'index.json'), JSON.stringify(index, null, 2) + '\n');

  const totals = reports.reduce(
    (a, r) => ({
      checked: a.checked + r.counts.checked,
      flagged: a.flagged + r.counts.flagged,
      unchecked: a.unchecked + r.counts.unchecked,
    }),
    { checked: 0, flagged: 0, unchecked: 0 },
  );
  console.log(
    `Audited ${reports.length} articles → ${OUT_DIR}\n` +
      `  ${totals.checked} claims checked · ${totals.flagged} flagged · ${totals.unchecked} unchecked`,
  );
}

main();
